apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: Tests assert
  name: demo-vm3
  namespace: default
  #namespace: suxess-it-qa
  labels:
    app: demo-vm3
    kubevirt.io/dynamic-credentials-support: 'true'
    #vm.kubevirt.io/template:  rhel9--
    vm.kubevirt.io/template:  rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: demo-vm3
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi # must be equal/greater Datasource!!
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: rhel9
#        vm.kubevirt.io/flavor: 
#        vm.kubevirt.io/workload: 
      creationTimestamp: null
      labels:
        kubevirt.io/domain: demo-vm3
#        kubevirt.io/size: 
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 3
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
#          rng: {}
#        features:
#          acpi: {}
#          smm:
#            enabled: true
#        firmware:
#          bootloader:
#            efi: {}
##        machine:
#          type: pc-q35-rhel9.2.0
        memory:
          guest: 6Gi
#        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: demo-vm3
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: testcnppwd1
              chpasswd: { expire: False }
          name: cloudinitdisk
